# Generated by Django 3.1.7 on 2021-04-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current_spending',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='budget',
            name='remaining_spending',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='max_spend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
