# Generated by Django 3.1.7 on 2021-04-28 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20210428_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deals.list'),
        ),
    ]
