# Generated by Django 3.1.7 on 2021-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_budget_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='max_spend',
            field=models.FloatField(default=400),
        ),
    ]
