# Generated by Django 3.1.7 on 2021-04-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20210428_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='current_spending',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='remaining_spending',
        ),
    ]
