# Generated by Django 3.1.7 on 2021-04-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20210428_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='No name', max_length=30),
        ),
    ]
