# Generated by Django 3.1.7 on 2021-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='default name', max_length=30),
        ),
    ]
