# Generated by Django 3.1.7 on 2021-04-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20210428_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.list'),
        ),
        migrations.AlterField(
            model_name='product',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.list'),
        ),
    ]
