# Generated by Django 3.1.7 on 2021-05-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_auto_20210428_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
