# Generated by Django 3.1.7 on 2021-05-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_auto_20210512_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
