# Generated by Django 3.1.7 on 2021-05-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_auto_20210513_0128'),
        ('deals', '0011_auto_20210514_0613'),
    ]

    operations = [
    ]
