# Generated by Django 3.1.7 on 2021-05-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_merge_20210514_1709 2'),
        ('deals', '0011_auto_20210430_1901'),
        ('deals', '0012_auto_20210516_1529'),
    ]

    operations = [
    ]
