# Generated by Django 3.1.7 on 2021-05-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_merge_20210519_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('comment_suggestion', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
    ]
