# Generated by Django 3.1.7 on 2021-05-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_merge_20210524_0415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
