# Generated by Django 3.1.7 on 2021-05-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_delete_watchlist'),
        ('deals', '0014_usersuggestions'),
    ]

    operations = [
    ]
