# Generated by Django 3.1.7 on 2021-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_merge_20210526_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('W', 'Watch List'), ('S', 'Shopping List')], max_length=1),
        ),
    ]
